### ISSUE TITLE
Plugins do not seem to properly restore state

### ISSUE THREAD

**Issue by Gert-dev** [flathub/net.sourceforge.liferea#3]
It appears that the settings of some plugins are not retained after a restart.

Steps to reproduce:

1. Open the plugins panel.
2. Enable the "WebKit Setting" plugin.
3. Open its preferences.
4. Disable "Auto Load Images".
5. Close Liferea.
6. Start Liferea again.
7. Going back to the preferences shows the setting appears to have reset.

This doesn't happen with the Liferea from the native Arch repositories. I don't exactly understand why this happens, since the settings _do_ appear to be persisted properly to `~/.var/app/net.sourceforge.liferea/config/liferea/plugins/webkitsetting/webkitsetting.ini`.

**Comment by bbhtt** [comment]
How did you install that plugin?

Downloading the external plugins apparently requires `git` which is not present inside the sandbox, expectedly; so it throws an error:

![Screenshot](https://user-images.githubusercontent.com/62639087/151394466-62c46fc9-7c14-470b-9ed3-519e7136ef3b.png)

**Comment by Gert-dev** [comment]
Ah, I must have worked around that by accident by copying my liferea configuration into the `.var/app` folder from the native Arch Linux build, as I was trying to migrate to the Flatpak. I copied over the plugins along that way, it seems.

**Comment by bbhtt** [comment]
Workaround: 

Keep the plugin config in `~/.config/liferea/plugins`, run Liferea with `$ flatpak run --filesystem=xdg-config/liferea/plugins net.sourceforge.liferea` this should allow reading and writing the plugin config and it should persist. If you only need read-only access to the config `$ flatpak run --filesystem=xdg-config/liferea/plugins:ro net.sourceforge.liferea`.

I tried including `git` to the manifest to allow installing the external plugins from inside the sandbox, but Liferea clones the plugin repo to `/tmp` and tries to copy them to `/home/user/.local/share/plugins`,(instead of `/home/user/.var/app/net.sourceforge.liferea/data/liferea/plugins`) to which it doesn't have access so it fails and no plugin gets installed.

I also tried to `cp -R` this https://github.com/mozbugbox/liferea-plugin-studio/tree/master/webkit-setting to `home/user/.var/app/net.sourceforge.liferea/data/liferea/plugins` but then Liferea shows the plugin as installed but no plugin config changes persist as it fails to create the `webkitsetting.ini` file, presumably due to lacking something in `/bin` inside the sandbox. I tried `strace`-ing but couldn't find what it needs.

Note. The issue is not limited to the external plugins only;  included ones like Get Focus plugin also fails to save and persist and config.
